//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.ApplicationModule.WarrantModule.Invoice {
    
    public partial class InvoicingDetails {
        protected SuperWebControl.FormHeader InvoiceComm;
        protected System.Web.UI.WebControls.Label Label2;
        protected SuperWebControl.DateControl InvoiceDate;
        protected System.Web.UI.WebControls.Button btnShow;
        protected System.Web.UI.WebControls.Label Label3;
        protected System.Web.UI.WebControls.Label DisplayNumberLabel;
        protected SuperWebControl.SuperGridview InvoiceSuperGridView;
        protected System.Web.UI.WebControls.Button btnsave;
        public new DefaultMaster Master {
            get {
                return ((DefaultMaster)(base.Master));
            }
        }
    }
}
