//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.WarrantModule {
    
    public partial class CashElectionProcess {
        protected SuperWebControl.FormHeader CashElectionHeader;
        protected System.Web.UI.WebControls.Label ResetDateLabel;
        protected System.Web.UI.WebControls.DropDownList ResetDateDropdown;
        protected System.Web.UI.WebControls.Label Label4;
        protected System.Web.UI.WebControls.DropDownList PositionDateDropdown;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.RadioButtonList OptionRadioButtonList;
        protected System.Web.UI.WebControls.Label Label3;
        protected System.Web.UI.WebControls.RadioButtonList ProcessRadioButtonList;
        protected System.Web.UI.WebControls.Label EventDateLabel;
        protected SuperWebControl.DateControl EventDate;
        protected System.Web.UI.WebControls.Label Label2;
        protected System.Web.UI.WebControls.Label DisplayNumberLaabel;
        protected SuperWebControl.SuperGridview CashElectionSuperGridView;
        protected SuperWebControl.SuperGridview CashElectionDetailSuperGridView;
        protected System.Web.UI.WebControls.Button CashExecutionNoneButton;
        protected System.Web.UI.WebControls.Button DealExecutionNoneButton;
        protected System.Web.UI.WebControls.Button ReportButton;
        protected System.Web.UI.WebControls.HiddenField HiddenField2;
        protected System.Web.UI.WebControls.HiddenField ExceptionDetails;
        public new DefaultMaster Master {
            get {
                return ((DefaultMaster)(base.Master));
            }
        }
    }
}
