//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.ApplicationModule.WarrantModule.Election {
    
    public partial class CommisionTrx {
        protected SuperWebControl.FormHeader CashElectionHeader;
        protected System.Web.UI.WebControls.Label ResetDateLabel;
        protected System.Web.UI.WebControls.DropDownList ResetDateDropdown;
        protected System.Web.UI.WebControls.Label EventDateLabel;
        protected SuperWebControl.DateControl EventDate;
        protected System.Web.UI.WebControls.Label Label2;
        protected System.Web.UI.WebControls.Label DisplayNumberLabel;
        protected SuperWebControl.SuperGridview WarrantCommSuperGridView;
        protected System.Web.UI.WebControls.Button WarrantCommButton;
        protected System.Web.UI.WebControls.Button ReportButton;
        protected System.Web.UI.WebControls.HiddenField ExceptionDetails;
        public new DefaultMaster Master {
            get {
                return ((DefaultMaster)(base.Master));
            }
        }
    }
}
