//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.ApplicationModule {
    
    public partial class uscRollover {
        protected Csla.Web.CslaDataSource WarantEventDS;
        protected System.Web.UI.WebControls.FormView FormView1;
        protected System.Web.UI.WebControls.HiddenField hdnStrikeRate;
        protected System.Web.UI.WebControls.HiddenField hdnPlannerFee;
        protected System.Web.UI.WebControls.HiddenField hdnRollOverAccNum;
        protected System.Web.UI.WebControls.HiddenField ExceptionDetails;
        protected System.Web.UI.WebControls.Literal ShowScript;
    }
}
