//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.ApplicationModule {
    
    public partial class WarrantElectionView {
        protected SuperWebControl.FormHeader FormHeader1;
        protected System.Web.UI.WebControls.Label PortfolioNumberLabel;
        protected System.Web.UI.WebControls.Label PortfolioNameLabel;
        protected System.Web.UI.WebControls.Label ApplicationNumberLabel;
        protected System.Web.UI.WebControls.Label AppReceivedDateLabel;
        protected System.Web.UI.WebControls.Label WarrantCodeLabel;
        protected System.Web.UI.WebControls.Label ResetDateLabel;
        protected System.Web.UI.WebControls.Label AvailableQtyLabel;
        protected System.Web.UI.WebControls.Label lblPlanner;
        protected System.Web.UI.WebControls.Label lblPlannerText;
        protected System.Web.UI.WebControls.PlaceHolder ElectionPlaceHolder;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.Button btnCancel;
        protected System.Web.UI.WebControls.Button btnVerify;
        protected System.Web.UI.WebControls.Button btnundoVerify;
        protected System.Web.UI.WebControls.Button btnPushToWias;
        protected System.Web.UI.WebControls.HiddenField ExceptionDetails;
        protected System.Web.UI.WebControls.Literal ShowScript;
        protected System.Web.UI.WebControls.HiddenField HiddenField2;
        protected System.Web.UI.WebControls.HiddenField hdnRetvalue;
    }
}
