//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.ApplicationModule.WarrantModule.Election {
    
    public partial class WarrantOngoingCommTrx {
        protected SuperWebControl.FormHeader CommissionElectionHeader;
        protected SuperWebControl.DateControl MonthStartDate;
        protected SuperWebControl.DateControl MonthEndDate;
        protected System.Web.UI.WebControls.Panel PnlIncluExclusive;
        protected System.Web.UI.WebControls.RadioButtonList CommissionRadioButtonList;
        protected System.Web.UI.WebControls.Label Label2;
        protected System.Web.UI.WebControls.Label DisplayNumberLabel;
        protected System.Web.UI.WebControls.Label lblNew;
        protected System.Web.UI.WebControls.Label lblNewlyCreated;
        protected System.Web.UI.WebControls.Label lblAlready;
        protected System.Web.UI.WebControls.Label lblAlreadyCreated;
        protected SuperWebControl.SuperGridview WarrantCommSuperGridView;
        protected System.Web.UI.WebControls.Button WarrantCommButton;
        protected System.Web.UI.WebControls.Button WarrantGenerateCommBtn;
        protected System.Web.UI.WebControls.Button ReportButton;
        protected System.Web.UI.WebControls.HiddenField ExceptionDetails;
        protected System.Web.UI.WebControls.HiddenField hdnCommissionStartDate;
        protected System.Web.UI.WebControls.HiddenField hdnCommissionEndDate;
        protected System.Web.UI.WebControls.HiddenField hdnReturnValue;
        public new DefaultMaster Master {
            get {
                return ((DefaultMaster)(base.Master));
            }
        }
    }
}
